# Generated by Django 6.0 on 2026-04-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='hero_slides/')),
                ('link_text', models.CharField(blank=True, default='View Catalog', max_length=100)),
                ('link_url', models.CharField(blank=True, default='/products/', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Sort order for slides (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
