# Generated by Django 6.0 on 2026-04-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equip', '0002_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Format: +919328090749', max_length=50)),
                ('working_hours', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_policy', models.TextField(blank=True, help_text='HTML or plain text for Warranty Policy')),
                ('shipping_info', models.TextField(blank=True, help_text='HTML or plain text for Shipping Info')),
                ('terms_conditions', models.TextField(blank=True, help_text='HTML or plain text for Terms & Conditions')),
            ],
            options={
                'verbose_name': 'Support Page Content',
                'verbose_name_plural': 'Support Page Content',
            },
        ),
    ]
